name: 
king
on:
[push]
jobs:
 build:
 runs-on: ubuntu-latest
 steps:
 - uses: actions/checkout@v1
 - name: Run a one-line script
 run: echo Hello, world!
 - name: java version
 run: java -version
 - name: mvn version
 run: mvn --version
 - name: docker version
 run: docker -v
